services:
  - type: web
    name: sistema-calzado
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python datos_iniciales.py
    startCommand: gunicorn app_v2:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
