databases:
  - name: calzado-db
    plan: free
    databaseName: calzado
    user: calzado_user

services:
  - type: web
    name: sistema-calzado
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_v2:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calzado-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11.0"
